package typed

//go:generate go install github.com/joeshaw/gengen

//go:generate gengen -o int github.com/itsmontoya/mailbox int
//go:generate gengen -o int8 github.com/itsmontoya/mailbox int8
//go:generate gengen -o int16 github.com/itsmontoya/mailbox int16
//go:generate gengen -o int32 github.com/itsmontoya/mailbox int32
//go:generate gengen -o int64 github.com/itsmontoya/mailbox int64
//go:generate gengen -o uint github.com/itsmontoya/mailbox uint
//go:generate gengen -o uint8 github.com/itsmontoya/mailbox uint8
//go:generate gengen -o uint16 github.com/itsmontoya/mailbox uint16
//go:generate gengen -o uint32 github.com/itsmontoya/mailbox uint32
//go:generate gengen -o uint64 github.com/itsmontoya/mailbox uint64
//go:generate gengen -o uintptr github.com/itsmontoya/mailbox uintptr
//go:generate gengen -o pointer github.com/itsmontoya/mailbox unsafe.Pointer
//go:generate gengen -o struct github.com/itsmontoya/mailbox struct{}
//go:generate gengen -o float32 github.com/itsmontoya/mailbox float32
//go:generate gengen -o float64 github.com/itsmontoya/mailbox float64
//go:generate gengen -o complex64 github.com/itsmontoya/mailbox complex64
//go:generate gengen -o complex128 github.com/itsmontoya/mailbox complex128
//go:generate gengen -o byte github.com/itsmontoya/mailbox byte
//go:generate gengen -o rune github.com/itsmontoya/mailbox rune
//go:generate gengen -o string github.com/itsmontoya/mailbox string
//go:generate gengen -o iface github.com/itsmontoya/mailbox MailboxIface

//go:generate gengen -o p_int github.com/itsmontoya/mailbox *int
//go:generate gengen -o p_int8 github.com/itsmontoya/mailbox *int8
//go:generate gengen -o p_int16 github.com/itsmontoya/mailbox *int16
//go:generate gengen -o p_int32 github.com/itsmontoya/mailbox *int32
//go:generate gengen -o p_int64 github.com/itsmontoya/mailbox *int64
//go:generate gengen -o p_uint github.com/itsmontoya/mailbox *uint
//go:generate gengen -o p_uint8 github.com/itsmontoya/mailbox *uint8
//go:generate gengen -o p_uint16 github.com/itsmontoya/mailbox *uint16
//go:generate gengen -o p_uint32 github.com/itsmontoya/mailbox *uint32
//go:generate gengen -o p_uint64 github.com/itsmontoya/mailbox *uint64
//go:generate gengen -o p_uintptr github.com/itsmontoya/mailbox *uintptr
//go:generate gengen -o p_pointer github.com/itsmontoya/mailbox *unsafe.Pointer
//go:generate gengen -o p_struct github.com/itsmontoya/mailbox *struct{}
//go:generate gengen -o p_float32 github.com/itsmontoya/mailbox *float32
//go:generate gengen -o p_float64 github.com/itsmontoya/mailbox *float64
//go:generate gengen -o p_complex64 github.com/itsmontoya/mailbox *complex64
//go:generate gengen -o p_complex128 github.com/itsmontoya/mailbox *complex128
//go:generate gengen -o p_byte github.com/itsmontoya/mailbox *byte
//go:generate gengen -o p_rune github.com/itsmontoya/mailbox *rune
//go:generate gengen -o p_string github.com/itsmontoya/mailbox *string

//go:generate gengen -o sp_int github.com/itsmontoya/mailbox []*int
//go:generate gengen -o sp_int8 github.com/itsmontoya/mailbox []*int8
//go:generate gengen -o sp_int16 github.com/itsmontoya/mailbox []*int16
//go:generate gengen -o sp_int32 github.com/itsmontoya/mailbox []*int32
//go:generate gengen -o sp_int64 github.com/itsmontoya/mailbox []*int64
//go:generate gengen -o sp_uint github.com/itsmontoya/mailbox []*uint
//go:generate gengen -o sp_uint8 github.com/itsmontoya/mailbox []*uint8
//go:generate gengen -o sp_uint16 github.com/itsmontoya/mailbox []*uint16
//go:generate gengen -o sp_uint32 github.com/itsmontoya/mailbox []*uint32
//go:generate gengen -o sp_uint64 github.com/itsmontoya/mailbox []*uint64
//go:generate gengen -o sp_uintptr github.com/itsmontoya/mailbox []*uintptr
//go:generate gengen -o sp_pointer github.com/itsmontoya/mailbox []*unsafe.Pointer
//go:generate gengen -o sp_struct github.com/itsmontoya/mailbox []*struct{}
//go:generate gengen -o sp_float32 github.com/itsmontoya/mailbox []*float32
//go:generate gengen -o sp_float64 github.com/itsmontoya/mailbox []*float64
//go:generate gengen -o sp_complex64 github.com/itsmontoya/mailbox []*complex64
//go:generate gengen -o sp_complex128 github.com/itsmontoya/mailbox []*complex128
//go:generate gengen -o sp_byte github.com/itsmontoya/mailbox []*byte
//go:generate gengen -o sp_rune github.com/itsmontoya/mailbox []*rune
//go:generate gengen -o sp_string github.com/itsmontoya/mailbox []*string

//go:generate gengen -o s_int github.com/itsmontoya/mailbox []int
//go:generate gengen -o s_int8 github.com/itsmontoya/mailbox []int8
//go:generate gengen -o s_int16 github.com/itsmontoya/mailbox []int16
//go:generate gengen -o s_int32 github.com/itsmontoya/mailbox []int32
//go:generate gengen -o s_int64 github.com/itsmontoya/mailbox []int64
//go:generate gengen -o s_uint github.com/itsmontoya/mailbox []uint
//go:generate gengen -o s_uint8 github.com/itsmontoya/mailbox []uint8
//go:generate gengen -o s_uint16 github.com/itsmontoya/mailbox []uint16
//go:generate gengen -o s_uint32 github.com/itsmontoya/mailbox []uint32
//go:generate gengen -o s_uint64 github.com/itsmontoya/mailbox []uint64
//go:generate gengen -o s_uintptr github.com/itsmontoya/mailbox []uintptr
//go:generate gengen -o s_pointer github.com/itsmontoya/mailbox []unsafe.Pointer
//go:generate gengen -o s_struct github.com/itsmontoya/mailbox []struct{}
//go:generate gengen -o s_float32 github.com/itsmontoya/mailbox []float32
//go:generate gengen -o s_float64 github.com/itsmontoya/mailbox []float64
//go:generate gengen -o s_complex64 github.com/itsmontoya/mailbox []complex64
//go:generate gengen -o s_complex128 github.com/itsmontoya/mailbox []complex128
//go:generate gengen -o s_byte github.com/itsmontoya/mailbox []byte
//go:generate gengen -o s_rune github.com/itsmontoya/mailbox []rune
//go:generate gengen -o s_string github.com/itsmontoya/mailbox []string
//go:generate gengen -o s_iface github.com/itsmontoya/mailbox []MailboxIface
